## **LABORATORY 8** - *Pytorch & Tensorflow*
#### ANEESH KRISHNA RAMESH - 8914620 
---
---

## ***Verifying Jupyter kernels***

In [49]:
!jupyter kernelspec list

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Available kernels:
  pytorch            /Users/amby/Library/Jupyter/kernels/pytorch
  tensorflow         /Users/amby/Library/Jupyter/kernels/tensorflow
  jupyternotebook    /usr/local/share/jupyter/kernels/jupyternotebook
  python3            /usr/local/share/jupyter/kernels/python3


In [50]:
import sys
import torch

## ***Verifying Pytorch & Tensorflow***

In [51]:
#Test pytorch
try:
    import torch
    print(f'Tensor: {torch.tensor([10, 10])}')
    print(f'PyTorch version: {torch.__version__}')    
    print('Succeeded')
except:
    print("Didn't succeed")

Tensor: tensor([10, 10])
PyTorch version: 2.0.0
Succeeded


In [52]:
#Test tensorflow
try:
    import tensorflow as tf
    print(f'Tensor: {tf.constant([10, 10])}')
    print(f'Tensorflow version: {tf.__version__}')    
    print('Succeeded')
except:
    print("Didn't succeed")

Tensor: [10 10]
Tensorflow version: 2.12.0
Succeeded


> ### ***NOTE :***
> ##### **You might see a notification of AVX2 FMA, it is because the computer i am compiling this in a computer with a processor that may support AVX2. TensorFlow is merely indicating that the installed version is configured to leverage AVX and AVX2 operations by default in specific scenarios. It's not an error; rather, it's a notification that TensorFlow can optimize computation by utilizing your CPU's features.**

> #### 

## ***Question 1*** -  
### 1. Calculate the dot product between two vectors each of length 3
### 2. Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)

In [53]:
#1.1 
v1 = torch.tensor([3.0,2.0,1.0])
v2 = torch.tensor([1.0,2.0,3.0])

dot = torch.dot(v1,v2)
#OR
dot = v1.dot(v2)

print("Torch Dot Product : ",dot)


Torch Dot Product :  tensor(10.)


In [54]:
#1.2 
m1 = torch.tensor([[9., 8.],[7., 6.]])
m2 = torch.tensor([[2., 3.],[4., 5.]])

mul = torch.matmul(m1, m2)
#OR 
mul = m1.matmul(m2)

print("Torch Matrix Multiplication : \n",mul)



Torch Matrix Multiplication : 
 tensor([[50., 67.],
        [38., 51.]])


## ***Question 2*** -
### 1. Calculate the dot product between the same vectors as above (re-define them in Tensorflow)
### 2. Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow)

In [55]:
#2 Tensorflow
import tensorflow as tf

In [56]:
#2.1 
v1 = tf.constant([3.0,2.0,1.0])
v2 = tf.constant([1.0,2.0,3.0])

dot = tf.tensordot(v1,v2,axes=1)

print("TF Dot Product  Numpy:", dot.numpy())
print("TF Dot Product  :", dot)

TF Dot Product  Numpy: 10.0
TF Dot Product  : tf.Tensor(10.0, shape=(), dtype=float32)


In [57]:
# 2.2
m1 = tf.constant([[9., 8.],[7., 6.]])
m2 = tf.constant([[2., 3.],[4., 5.]])

mul = tf.matmul(m1,m2)

print("TF Matrix Multiplication Numpy:\n", mul.numpy(),"\n")
print("TF Matrix Multiplication :\n", mul,"\n")
print("TF Matrix Shape:", mul.shape,"\n")


TF Matrix Multiplication Numpy:
 [[50. 67.]
 [38. 51.]] 

TF Matrix Multiplication :
 tf.Tensor(
[[50. 67.]
 [38. 51.]], shape=(2, 2), dtype=float32) 

TF Matrix Shape: (2, 2) 



---
---